namespace DeskBridge.Core.Agent;

public static class AgentToolDefinitions
{
    public static IReadOnlyList<object> All { get; } =
    [
        new { type = "code_interpreter", container = new { type = "auto" } },
        Function("inspect_local_file", "Inspect a file inside the current run directory and return size, hash, type, and extracted text metadata.",
            ObjectSchema(new { path = StringProperty("Absolute path inside the current run directory.") }, ["path"])),
        Function("read_text_file", "Read bounded UTF-8 text from the preserved source or a candidate inside the current run directory.",
            ObjectSchema(new { path = StringProperty("Absolute path inside the current run directory."), maxCharacters = IntegerProperty("Maximum characters from 100 to 50000.", 100, 50_000) }, ["path", "maxCharacters"])),
        Function("write_text_file", "Write a complete UTF-8 candidate inside the current run directory. Use only for text, code, CSV, JSON, HTML, or Markdown.",
            ObjectSchema(new { path = StringProperty("Absolute destination inside the current run directory."), content = StringProperty("Complete file content."), overwrite = BooleanProperty("Whether an existing candidate may be replaced.") }, ["path", "content", "overwrite"])),
        Function("list_folder", "List direct children of a folder inside the current run directory.",
            ObjectSchema(new { path = StringProperty("Absolute folder path inside the current run directory.") }, ["path"])),
        Function("save_generated_file", "Download a file generated by Code Interpreter into the local run versions folder, then inspect it. Call this for every candidate artifact before finalizing.",
            ObjectSchema(new { file_id = StringProperty("Generated OpenAI file ID."), filename = StringProperty("Safe filename including extension."), claimed_score = IntegerProperty("Provisional quality score from 0 to 100.", 0, 100), summary = StringProperty("What changed in this candidate.") }, ["file_id", "filename", "claimed_score", "summary"])),
        Function("complete_task", "Select the best inspected local candidate and complete the task. Do not call until requirements were checked against evidence.",
            ObjectSchema(new { best_path = StringProperty("Absolute path to an existing inspected candidate inside the run directory."), score = IntegerProperty("Evidence-backed score from 0 to 100.", 0, 100), summary = StringProperty("Concise completion summary."), requirements_met = ArrayProperty("Specific requirements that passed."), remaining_issues = ArrayProperty("Known remaining issues; empty when none.") }, ["best_path", "score", "summary", "requirements_met", "remaining_issues"]))
    ];

    private static object Function(string name, string description, object parameters) =>
        new { type = "function", name, description, strict = true, parameters };
    private static object ObjectSchema(object properties, string[] required) =>
        new { type = "object", properties, required, additionalProperties = false };
    private static object StringProperty(string description) => new { type = "string", description };
    private static object IntegerProperty(string description, int minimum, int maximum) => new { type = "integer", description, minimum, maximum };
    private static object BooleanProperty(string description) => new { type = "boolean", description };
    private static object ArrayProperty(string description) => new { type = "array", description, items = new { type = "string" } };
}
